### ISSUE TITLE
High CPU load when running in staging environment

### ISSUE THREAD

**Issue by tompesman** [ileitch/rapns#28]
Hello,

I have 2 rapns processes running on the same server, one process runs in the production environment, the other one runs in the staging environment. In the production environment the CPU load is 4-5% and in the staging environment the load is around 25%. I suspect the logging of the SQL requests in the staging.log file increases the CPU load. Is this the expected behavior? Can I control the level of logging from the configuration file? If not, you can consider this issue a feature request. 

Regards,

Tom

**Comment by ileitch** [comment]
Even 4-5% sounds very high. Can you please paste your rapns.yml?

**Comment by tompesman** [comment]
basically the default configuration file with the production part copied for the staging environment:

``` yml
development:
  certificate: development.pem
  certificate_password:

  push:
    host: gateway.sandbox.push.apple.com
    port: 2195
    poll: 2
    connections: 3

  feedback:
    host: feedback.sandbox.push.apple.com
    port: 2196
    poll: 60

staging:
  certificate: staging.pem
  certificate_password:
  airbrake_notify: false
  pid_file: tmp/pids/rapns.pid

  push:
    host: gateway.push.apple.com
    port: 2195
    poll: 2
    connections: 3

  feedback:
    host: feedback.push.apple.com
    port: 2196
    poll: 60

production:
  certificate: production.pem
  certificate_password:
  airbrake_notify: false
  pid_file: tmp/pids/rapns.pid

  push:
    host: gateway.push.apple.com
    port: 2195
    poll: 2
    connections: 3

  feedback:
    host: feedback.push.apple.com
    port: 2196
    poll: 60
```
